// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoNDcct3ORHnpODR5PbZcuWvVO3G4uBKE',
    appId: '1:31757389042:web:6dd3d0381d21fd8d46546b',
    messagingSenderId: '31757389042',
    projectId: 'my-companion-app-flutterfire',
    authDomain: 'my-companion-app-flutterfire.firebaseapp.com',
    storageBucket: 'my-companion-app-flutterfire.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBojNAa9b_dNb6T1JEqf-8_4CZSC87x7ho',
    appId: '1:31757389042:android:ff7e1ce79917219146546b',
    messagingSenderId: '31757389042',
    projectId: 'my-companion-app-flutterfire',
    storageBucket: 'my-companion-app-flutterfire.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeM2a4bvGxFmoEfmIxcfHZYJsBi6Ec_WI',
    appId: '1:31757389042:ios:9e4c83dae39c7d8a46546b',
    messagingSenderId: '31757389042',
    projectId: 'my-companion-app-flutterfire',
    storageBucket: 'my-companion-app-flutterfire.appspot.com',
    iosClientId: '31757389042-f4v7ksln13ulqua5177jv02c5vdhmlbr.apps.googleusercontent.com',
    iosBundleId: 'com.example.companionapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeM2a4bvGxFmoEfmIxcfHZYJsBi6Ec_WI',
    appId: '1:31757389042:ios:2527d469fcf8b00d46546b',
    messagingSenderId: '31757389042',
    projectId: 'my-companion-app-flutterfire',
    storageBucket: 'my-companion-app-flutterfire.appspot.com',
    iosClientId: '31757389042-s4timdvevad04olnhcv37dgjou2085pg.apps.googleusercontent.com',
    iosBundleId: 'com.example.companionapp.RunnerTests',
  );
}
